<a href="https://colab.research.google.com/github/Savanaarnett/Data_science/blob/main/Arnettlab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Loops

In [2]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [3]:
#created a range of numbers

In [4]:
for i in range(5,8):
  print(i)

5
6
7


In [5]:
#had the system print the range between 5-8

In [6]:
for i in range(3):
  print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


In [7]:
#Then gave the title "Test Number" to each line

#Functions

In [8]:
def square(x):
    return x**2

In [9]:
#adding "def" in the beginning creates a function

In [10]:
square(5)

25

In [11]:
#This shows that the function squared the number within "square"

In [12]:
square(6)

36

In [13]:
square(74836)

5600426896

In [14]:
square(square(6))

1296

In [15]:
square(square(square(6)))

1679616

In [16]:
def add_two(x):
    return x+2

In [64]:
#This coding equates the words "add_two" with the actual function "x+2"

In [17]:
add_two(5)

7

In [65]:
#The outcome of the previous coding

In [18]:
choice = "apple"

In [66]:
#This is coding a choice of apple for the word 'choice'.

In [19]:
if choice == "apple":
    print("You choose apples.")
else:
    print("You did NOT choose apples.")

You choose apples.


In [67]:
#This coding gives the user a certain answer based on the choice they input in the system. The function 'print' will automatically write what you put into the system back to the user.

In [20]:
choice = "orange"

In [68]:
#Added another choice.

In [21]:
if choice == "apple":
    print("You choose apples.")
elif choice == "orange":
    print("You choose oranges.")
else:
    print("You did not choose apples or oranges.")

You choose oranges.


In [69]:
#This is adding more print based on the choice the user makes on what fruit they like.

In [22]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose oranges.
Thank you, shop again!


In [70]:
#You can put as many 'prints' as you want to give an automatic response when the user interacts with the system.

#User Input

In [23]:
choice = input("Please enter your choice (i.e. apple):")

Please enter your choice (i.e. apple):apple


In [71]:
#This allows the user to directly input a choice.

In [24]:
choice

'apple'

In [25]:
import numpy as np

In [26]:
np.random.permutation(52)

array([28, 34,  6,  1, 19, 41, 14, 11, 40, 13, 15, 21,  7, 46, 30, 45, 39,
       29,  2, 42, 27, 12,  5, 10, 25, 32, 47, 43, 49, 17, 48,  4,  3, 26,
       23, 51, 31, 18, 20, 33, 36, 37, 35, 50, 38, 24, 16,  9, 22,  8, 44,
        0])

In [72]:
#This picks random numbers between 0-52.

In [27]:
cards = np.random.permutation(52)

In [73]:
#This sets that there are only 52 cards

In [28]:
cards

array([40, 41, 10, 47,  0, 11, 29,  1,  9,  4, 37, 22, 33,  2, 39, 21, 18,
       45, 12, 50, 20, 25, 27,  3, 36, 19, 48, 13,  7, 35, 43, 28, 31, 32,
       24, 34, 30,  5, 26, 17,  6, 49, 16, 51, 44, 14, 46, 15, 42, 38,  8,
       23])

In [29]:
cards[0]

40

In [74]:
#Input a number and thats the card in that slot. At slot 0 uts card 40.

In [30]:
cards[6]

29

In [31]:
cards[3]

47

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [75]:
#This img function allows for a url to show an image.

In [32]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [76]:
#This arranges the cards from 0-52

In [33]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [77]:
#This aranges the 52 cards as columns and in order. The 1st column is 1 and the 2nd is 2 etc...

In [34]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [35]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [78]:
#This is adding the names to the cards within the deck.

In [36]:
suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [79]:
#This lists all the suits as specified in the previous coding.

In [37]:
suits[0]

'Clubs'

In [80]:
#By adding a number within the brackets it lists the specific suit you want.

In [38]:
names[1]

'Two'

In [39]:
def card_name(card_number):

    suit = card_number//13
    name = card_number%13

    return names[name]  +  "of"  +  suits[suit]

In [ ]:
#This function says based on the card name it will return the " name "of" suit ".

In [40]:
card_name(0)

'AceofClubs'

In [81]:
#The output of the previous function.

In [41]:
card_name(51)

'KingofDiamonds'

In [42]:
cards = np.random.permutation(52)

In [82]:
#This specifies that there are 52 cards and a random one can be picked.

In [43]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [83]:
#This assigns a card to the certain spot in the virtual deck.

In [44]:
top_of_deck,second_card_in_deck,last_card_in_deck

('JackofClubs', 'NineofHearts', 'TwoofHearts')

In [84]:
#This lists the cards in that spot

In [45]:
for i in range(5):
    print(card_name(cards[i]))

JackofClubs
NineofHearts
QueenofSpades
FiveofHearts
TwoofSpades


In [85]:
#This prints random 5 random cards based and it can change based on the number (range) input.


In [46]:
for i in range(10):
    print(card_name(cards[i]))

JackofClubs
NineofHearts
QueenofSpades
FiveofHearts
TwoofSpades
JackofSpades
TwoofDiamonds
TwoofClubs
SevenofSpades
TenofClubs


In [86]:
#Lists 10 cards

In [47]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [87]:
#adds more images for the cards

In [48]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [88]:
#This is adding the lists for the suit and card.

In [49]:
i = np.random.randint(4)
j = np.random.randint(13)

In [89]:
#This makes the number random.

In [50]:
i,j

(0, 8)

In [51]:
suit[i]

'k'

In [52]:
card[j]

'9'

In [53]:
from IPython.core.display import display, HTML

In [90]:
#This allows for images to show.

In [54]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [91]:
#This attatches the img to the function

In [55]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [56]:
show_img(img)

In [92]:
#This shows that the img attatched correctly to the function. It produced the exact card.

In [59]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [93]:
#This function causes the output to be the suit and the card number

In [60]:
card_image(3)

'k4'

In [94]:
#The example of the function above. It produced k4

In [61]:
img = card_url_head + card_image(3) + card_url_tail

In [62]:
show_img(img)

In [95]:
#It produced another card.

In [63]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)

In [96]:
#The range was input and it produced all 52 cards because the range was set to all 52.